packages:
  - packages/*
  - examples/*
  - website

allowBuilds:
  esbuild: true
  msgpackr-extract: false

onlyBuiltDependencies:
  - esbuild
catalog:
  "@effect/platform": ^0.96.1
  "@effect/rpc": ^0.75.1
  "@types/node": ^25.9.2
  effect: ^3.21.3
  tsx: ^4.22.4
  typescript: ^6.0.3
  vite-plus: ^0.2.1
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
